### ISSUE TITLE
Failed expect test error message is bad

### ISSUE THREAD

**Issue by ezyang** [ezyang/expecttest#2]
```
======================================================================                            
FAIL: test_conflicting_ufunc (__main__.TestCodegenModel)                                          
----------------------------------------------------------------------                            
Traceback (most recent call last):                                                                
  File "/data/users/ezyang/pytorch-tmp/tools/test/test_codegen_model.py", line 13, in assertErrorI
nline                                                                                             
    parse_native_yaml_struct(es)                                                                    File "/data/users/ezyang/pytorch-tmp/tools/codegen/gen.py", line 98, in parse_native_yaml_struct
    func, m = NativeFunction.from_yaml(e, loc)                                                      File "/data/users/ezyang/pytorch-tmp/tools/codegen/model.py", line 509, in from_yaml            
    kernel=ufunc.schema_kernel_name(func, dispatch_key),                                            File "/data/users/ezyang/pytorch-tmp/tools/codegen/api/ufunc.py", line 15, in schema_kernel_name
    assert func.is_out_fn(), "ufunc.kernel_name should only be invoked on out schemas"            AssertionError: ufunc.kernel_name should only be invoked on out schemas                           
  in <stdin>:1:                                                                                   
    foo.out(Tensor self, Tensor other) -> Tensor                                                  
                                                                                                  
During handling of the above exception, another exception occurred:                               
                                                                                                  
Traceback (most recent call last):                                                                
  File "/data/users/ezyang/pytorch-tmp/tools/test/test_codegen_model.py", line 29, in test_conflic
ting_ufunc                                                                                        
    self.assertErrorInline(yaml_str, '''''')                                                      
  File "/data/users/ezyang/pytorch-tmp/tools/test/test_codegen_model.py", line 15, in assertErrorI
nline                                                                                             
    self.assertExpectedInline(str(e), expect, skip=1)                                             
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.10/site-packages/expecttest/__init__.py", l
ine 262, in assertExpectedInline                                                                  
    self.assertMultiLineEqualMaybeCppStack(expect, actual, msg=help_text)                         
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.10/site-packages/expecttest/__init__.py", l
ine 287, in assertMultiLineEqualMaybeCppStack                                                     
    self.assertEqual(actual[len(expect): end_header], cpp_stacktrace_header)                      
AssertionError: 'ufunc.kernel_name shou' != '\nException raised from'                             
- ufunc.kernel_name shou                                                                          
+                                                                                                 
Exception raised from 
```

not sure why multiline assert equals isn't working properly

**Comment by ezyang** [comment]
also the help text is missing

**Comment by anjali411** [comment]
Also the error message for multiline matching is quite unreadable:
```
======================================================================
FAIL: test_correct_module_names (__main__.TestPublicBindings)
An API is considered public, if  its  `__module__` starts with `torch.`
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/fsx/users/chourdiaanjali/tree2/test/test_public_bindings.py", line 332, in test_correct_module_names
    self.assertExpected(str(allow_list), 'api_checks')
  File "/fsx/users/chourdiaanjali/tree2/torch/testing/_internal/common_utils.py", line 2332, in assertExpected
    self.assertMultiLineEqual(expected, s)
AssertionError: "[('t[281318 chars]ing'), ('torch', 'Set', 'typing'), ('torch', '[17563 chars]ne)]" != "[('t[281318 chars]ing')]"

----------------------------------------------------------------------
Ran 1 test in 2.181s

FAILED (failures=1)
```
